APPNAME: graphite

# URL base for a Metricfire instance. (internalapi)
MFURL: http://localhost:8000/internalapi/graphite

DATABASES:
   default:
      NAME: hostedgraphite
      ENGINE: django.db.backends.mysql
      USER: hostedgraphite
      PASSWORD: '7-bVYNfboccD'
      HOST: ''
      PORT: ''

