APPNAME: graphite

# URL base for a Metricfire instance. (internalapi)
MFURL: http://localhost:8000/internalapi/graphite
MFTIMEOUT: 20

MEMCACHE_HOSTS: ['127.0.0.1:11211']

DATABASES:
   default:
      NAME: hostedgraphite
      ENGINE: django.db.backends.mysql
      USER: hostedgraphite
      PASSWORD: '7-bVYNfboccD'
      HOST: ''
      PORT: ''

GRAPHITE:
   enabled: true
   host: carbon.hostedgraphite.com
   port: 2003
   key: 7aa099bd-29ae-478f-b1aa-6b4b4e2ef878
   debug: false

AUTH_PROFILE_MODULE: account.UserProfile

# Number of seconds beyond which metric data fetching will be stopped and the
# request will proceed with only partial data.
FETCH_TIMEOUT: 30
